[Configuration] Add more fine-grained permissions to configurations
pimcore/data-importer pull request #122
Opened 2021-11-12 13:47 UTC by dvesh3

Related to https://github.com/pimcore/data-hub/pull/438

2021-11-29 10:11 UTC, fashxp commented
probably add a migration that re-installs the bundle ... so that already installed bundles don't need to be installed again?

2021-11-29 10:39 UTC, dvesh3 commented
> probably add a migration that re-installs the bundle ... so that already installed bundles don't need to be installed again?

@fashxp yes, should be handled [here](https://github.com/pimcore/data-importer/pull/122/files#diff-cabfa55630333e0f5e9327612d0d45d3dccec18765ae7d475a6d6d1c3afd3b36R38) as the migration returns true for `checkBundleInstalled`

2021-11-29 10:46 UTC, fashxp commented
ahh, oversaw that, perfect 👍

2021-12-13 10:45 UTC, fashxp requested changes

2021-12-13 10:45 UTC, fashxp commented on src/DependencyInjection/PimcoreDataImporterExtension.php
> +    public function prepend(ContainerBuilder $container)
also need to add `PrependExtensionInterface` in implements statement of class.

2021-12-14 20:17 UTC, blankse commented on composer.json
>      "pimcore/pimcore": "^6.9 || ^10.0",
```suggestion
    "pimcore/pimcore": "^10.2",
```

2021-12-14 20:17 UTC, blankse commented on composer.json
> +    "pimcore/data-hub": "^0.7 || ^1.2",
```suggestion
    "pimcore/data-hub": "^1.2",
```

2021-12-15 06:54 UTC, blankse commented on composer.json
>      "php": ">=7.4",
```suggestion
    "php": "^8.0",
```

2021-12-30 12:20 UTC, fashxp requested changes

2021-12-30 12:20 UTC, fashxp commented on src/Resources/public/js/pimcore/configuration/configItemDataObject.js
> -        if (!this.isValid(true)) {
why was that removed?

2022-01-05 08:55 UTC, fashxp approved these changes

2022-01-05 09:51 UTC, merged