Added Structured Table Type
pimcore/data-importer pull request #353
Opened 2023-08-31 07:59 UTC by mybabysexy

Implement #101

2023-08-31 08:01 UTC, mybabysexy commented
I have read the CLA Document and I hereby sign the CLA
recheck

2023-08-31 08:01 UTC, mybabysexy commented
recheck

2023-08-31 08:02 UTC, mybabysexy commented
I have read the CLA Document and I hereby sign the CLA

2023-08-31 08:04 UTC, mybabysexy commented
recheck

2024-01-29 09:53 UTC, fashxp requested changes
Thx very much. We would need some tweaks here and there though.

2024-01-29 09:53 UTC, fashxp commented on src/Mapping/Operator/Factory/AsStructuredTable.php
> +        return TransformationDataTypeService::DEFAULT_ARRAY;
we would need to introduce there an extra type which just allows assignment to structured table fields, like we have it for quantity value, gallery etc.

2024-01-29 09:53 UTC, fashxp commented on src/Mapping/Type/TransformationDataTypeService.php
> +            'structuredTable'
should be moved to an extra type...

2024-01-29 09:53 UTC, fashxp commented on src/Mapping/Operator/Factory/AsStructuredTable.php
> +            return (new StructuredTable($inputData))->getHtmlTable(
Why return a html table here? 
Shouldn't be that in `generateResultPreview`, as for example [here](https://github.com/pimcore/data-importer/blob/43fb4128dac8284fcfc29b7ec6d2ffed99c4d22b/src/Mapping/Operator/Factory/Gallery.php#L73)

2024-01-29 09:53 UTC, fashxp commented on src/Mapping/Operator/Factory/AsStructuredTable.php
> +                }, array_keys($inputData), array_keys(array_values($inputData)[0])),
`$inputData` might be empty/null ... will result in errors at this place.

2024-02-27 11:46 UTC, fashxp commented
@mybabysexy :ping_pong: did you already have a chance to take a look at my comments?

2024-04-30 08:08 UTC, fashxp commented
@mybabysexy 🏓

2024-06-10 13:18 UTC, fashxp commented
@mybabysexy :ping_pong: any chance we could continue the discussion here?

2024-06-10 13:26 UTC, mybabysexy commented
> @mybabysexy 🏓 any chance we could continue the discussion here?

hi, sorry I'm no longer working with Pimcore or PHP so I don't think that I can continue with this PR

2024-06-10 15:02 UTC, fashxp commented
> > @mybabysexy 🏓 any chance we could continue the discussion here?
> 
> hi, sorry I'm no longer working with Pimcore or PHP so I don't think that I can continue with this PR

thx for the information.

2024-06-10 15:02 UTC, fashxp commented
closing due to inactivity

2024-06-10 15:02 UTC, closed without merging