[Feature]: Automaticaly set imported element userModification
pimcore/data-importer pull request #418
Opened 2024-07-16 11:25 UTC by root913

This PR solves problem of identifying who is the author of object change for manualy triggered imports.

As of now every object that was changed by import had userModification set to 0 (that is system user). 
This change introduce new column "**userOwner**" to queue table that by default is set to 0.
If user manualy trigger import it's user id is passed to queue item and later in import process it is set to element userModification property.
This will not affect automatic/cron imports.

2024-07-16 11:28 UTC, root913 commented
I have read the CLA Document and I hereby sign the CLA

2024-08-16 06:18 UTC, mattamon requested changes
Hey @root913,

your PR looks good to me! Just some minor changes. I would always rather import the whole class instead of importing just a part like with Tool\Admin.

Also I would add a comment saying that the 0 is system user just to have it there. 

But other than that it looks solid!

Thank you for your contribution!

2024-08-16 06:18 UTC, mattamon commented on src/DataSource/Interpreter/AbstractInterpreter.php
> +use Pimcore\Tool;
```suggestion
use Pimcore\Tool\Admin;
```

2024-08-16 06:18 UTC, mattamon commented on src/DataSource/Interpreter/AbstractInterpreter.php
> +        $userOwner = Tool\Admin::getCurrentUser()?->getId() ?? 0;
```suggestion
        $userOwner = Admin::getCurrentUser()?->getId() ?? 0;
```

2024-08-16 06:18 UTC, mattamon commented on src/DataSource/Interpreter/AbstractInterpreter.php
> +        $userOwner = Tool\Admin::getCurrentUser()?->getId() ?? 0;
Could you please add a comment saying that if there is no user logged in we use the system user as `userOwner`

2024-08-20 12:07 UTC, root913 commented
I noticed that latest migration is specified in Installer class (method: getLastMigrationVersionClassName) - should i update it also?

2024-08-21 13:59 UTC, mattamon commented
@root913 

> I noticed that latest migration is specified in Installer class (method: getLastMigrationVersionClassName) - should i update it also?

That would be awesome yeah!

2024-08-22 05:50 UTC, mattamon commented on src/Queue/QueueService.php
> +            userOwner int unsigned NOT NULL DEFAULT \'0\',
```suggestion
            userOwner int unsigned NOT NULL DEFAULT 0,

```

I think we do not need the escaping here for 0 right?

2024-08-26 05:40 UTC, mattamon approved these changes
@root913 Thank you for all the changes and your contribution! This looks good to me!

2024-08-26 05:41 UTC, merged