Sissonen conditional conversion operator
pimcore/data-importer pull request #71
Opened 2021-07-26 07:52 UTC by sissonen

Mapping operator for converting original values. Details in doc/03_Configuration/06_Mapping_Configuration/02_Transformation_Pipeline.md

2021-08-03 13:20 UTC, sissonen commented
recheck

2021-08-03 15:37 UTC, fashxp commented
you have to type the phase `I have read the CLA Document  ... ` as comment as suggested in the comment above to make CLA happy. 
Thank you!

2021-08-03 15:40 UTC, fashxp requested changes
nice addition

2021-08-03 15:40 UTC, fashxp commented on src/Mapping/Operator/Simple/ConditionalConversion.php
> +        \Pimcore\Log\Simple::log("importerlog", $this->original . " " . $this->converted ." ".print_r($inputData, true));
can we remove that line? it will fill up the disk over time...

2021-08-04 06:58 UTC, sissonen commented
I have read the CLA Document and I hereby sign the CLA

2021-08-17 09:33 UTC, fashxp approved these changes

2021-08-17 09:33 UTC, fashxp commented
thx very much!

2021-08-17 09:33 UTC, merged